admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///flyte.org
  clientId: "**********"
  authType: ClientSecret
  insecure: false
logger:
  show-source: true
  level: 0
