name: Pull request check

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY_USER: evalsocket
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
  DOCKER_BUILDKIT: 1

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Add Flyte Project
        uses: dagger/dagger-for-github@v2
        with:
          workdir: "."
          args: project update github.com/evalsocket/flyte@main

      - name: Update Project
        uses: dagger/dagger-for-github@v2
        with:
          workdir: "."
          args: project update

      - name: Build & Serialize docker image
        uses: dagger/dagger-for-github@v2
        with:
          workdir: "."
          args: "do fast_serialize -l debug"
